
const STORAGE_KEY="coopchain_user_v1";
function getUser(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch{return null}}
function setUser(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p));refreshAuthUI()}
function clearUser(){localStorage.removeItem(STORAGE_KEY);refreshAuthUI()}
function refreshAuthUI(){const u=getUser();document.querySelectorAll("[data-auth-label]").forEach(e=>{e.textContent=u?`Hola, ${u.nombre}`:"Ingresar / Registrarse"});document.querySelectorAll("[data-requires-auth]").forEach(e=>{const t=e.getAttribute("href");if(!u&&t&&!t.includes("registro.html")){e.setAttribute("data-target",t);e.setAttribute("href",`registro.html?next=${encodeURIComponent(t)}`)}else if(u&&e.dataset.target){e.setAttribute("href",e.dataset.target)}});document.querySelectorAll("[data-user-only]").forEach(e=>e.classList.toggle("hidden",!u));document.querySelectorAll("[data-guest-only]").forEach(e=>e.classList.toggle("hidden",!!u))}
function handleRegistrationForm(){const f=document.querySelector('#registration-form');if(!f)return;const r=new URLSearchParams(location.search).get('next')||'dialogar-con-el-libro.html';f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f);const p={nombre:(d.get('nombre')||'').toString().trim(),apellido:(d.get('apellido')||'').toString().trim(),email:(d.get('email')||'').toString().trim(),empresa:(d.get('empresa')||'').toString().trim(),rol:(d.get('rol')||'').toString().trim(),createdAt:new Date().toISOString()};if(!p.nombre||!p.apellido||!p.email){alert('Completa nombre, apellido y email.');return}setUser(p);location.href=r})}
function injectPromptLinks(){document.querySelectorAll('[data-prompt]').forEach(b=>{b.addEventListener('click',()=>{const p=b.getAttribute('data-prompt');const box=document.querySelector('#starter-output');if(box){box.value=p;box.scrollIntoView({behavior:'smooth',block:'center'})}navigator.clipboard&&navigator.clipboard.writeText(p).catch(()=>{});const n=document.querySelector('#copied-note');if(n){n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),1800)}})})}
function bindLogout(){document.querySelectorAll('[data-logout]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();clearUser();location.href='index.html'}))}
document.addEventListener('DOMContentLoaded',()=>{refreshAuthUI();handleRegistrationForm();injectPromptLinks();bindLogout()});
